services:
  chat_db:
    image: postgres:latest
    container_name: chat_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5555:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
    networks:
      - chat_nest

  chat:
    container_name: chat
    build:
      context: .
      target: server
    env_file:
      - .env
    command: pnpm run prod
    depends_on:
      - chat_db
    ports:
      - 3001:3001
    networks:
      - chat_nest

networks:
  chat_nest:
    driver: bridge